[package]
name = "takeover"
version = "0.1.0"
authors = ["Thomas Runte <thomas@etnur.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/migrator/lib.rs"

[dependencies]

[dependencies.libc]
version = "0.2.70"
# git = "https://github.com/rust-lang/libc"

[dependencies.reqwest]
version = "0.10.4"
features = ["blocking", "json"]

[dependencies.url]
version = "2.1.1"

[dependencies.failure]
version = "0.1.8"

[dependencies.paw]
version = "1.0"

[dependencies.structopt]
version = "0.3.14"
features = ["paw"]

[dependencies.log]
version = "0.4.8"
features = ["std"]

[dependencies.regex]
 version = "=1.3.7"

[dependencies.nix]
 version = "0.17.0"

[dependencies.semver]
 version = "0.9.0"

[dependencies.serde]
 version = "1.0.110"
 features = ["derive"]

[dependencies.serde_yaml]
 version = "0.8.12"

[dependencies.serde_json]
version = "1.0.53"

[dependencies.flate2]
version = "1.0.14"

[dependencies.mod_logger]
version = "0.6.1"
# git = "https://github.com/samothx/ModuleLogger.git"
# branch = "support-ext-mods"

[dependencies.lazy_static]
version = "1.4.0"

[features]
raspberrypi3 = []
raspberrypi4-64 = []
intel-nuc = []

