[package]
name = "takeover"
version = "0.1.0"
authors = ["Thomas Runte <thomas@etnur.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/migrator/lib.rs"

[dependencies]

[dependencies.libc]
version = "0.2"
# git = "https://github.com/rust-lang/libc"

[dependencies.reqwest]
version = "0.10"
features = ["blocking", "json"]

[dependencies.url]
version = "2.1"

[dependencies.failure]
version = "0.1"

[dependencies.paw]
version = "1.0"

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.log]
version = "0.4"
features = ["std"]

[dependencies.regex]
 version = "1.0"

[dependencies.nix]
 version = "0.17"

[dependencies.semver]
 version = "0.9"

[dependencies.serde]
 version = "1.0"
 features = ["derive"]

[dependencies.serde_yaml]
 version = "0.8"

[dependencies.serde_json]
version = "1"

[dependencies.flate2]
version = "1.0"

[dependencies.mod_logger]
version = "0.6"
# git = "https://github.com/samothx/ModuleLogger.git"

[dependencies.lazy_static]
version = "1.4"

[features]
raspberrypi3 = []
raspberrypi4-64 = []
intel-nuc = []

