[package]
name = "takeover"
version = "0.1.0"
authors = ["Thomas Runte <thomas@etnur.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/migrator/lib.rs"

[dependencies]
failure = "*"
paw = "1.0.0"
structopt = { version = "0.3.7", features = ["paw"] }

log = { version = "^0.4.5", features = ["std"] }
mod_logger = { git = "https://github.com/samothx/ModuleLogger.git" }
libc = { git = "https://github.com/rust-lang/libc" }

regex = "1"
nix = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
flate2 = "1.0.14"

[features]
raspberrypi3 = []
raspberrypi4-64 = []
intel-nuc = []

